name: 🥰 Feedback
description: Submit a feedback
title: "Feedback Submission"
labels: "feedback"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feedback!
  - type: input
    id: description
    attributes:
      label: Description
      placeholder: Tell us what you see!
    validations:
      required: true
