name: Github Backup
on:
  schedule: [{cron: "0 0 * * FRI"}]
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
       - name: Run script
         run: chmod +x scripts/github-to-s3 && scripts/github-to-s3
         env: 
           BODY: ${{ github.event.issue.body }}
           CREATED_AT: ${{ github.event.issue.created_at }}
           USER_ID: ${{ github.event.issue.user.id }}
           USERNAME: ${{ github.event.issue.user.login }}
           AVATAR_URL: ${{ github.event.issue.user.avatar_url }}
