name: Fiverr Feedback
on:
  schedule: [{cron: "0 0 * * FRI"}]
  workflow_dispatch:
jobs:
  fiverr-feedback:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
       - name: Execute script
         run: python scripts/fiverr-feedback.py
       - name: Push changes
         run: |
               git config --global user.name "github-actions"
               git config --global user.email "github-actions@github.com"
               git add -A
               git commit -m "Update fiverr reviews"
               git push
