name: Generate Metrics
on:
  schedule: [{cron: "0 0 * * FRI"}]
  push: 
      branches: [master]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 📈 Generate Statistics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/statistics.svg
          user: abdulrahman1s
          template: classic
          base: activity, community, repositories
          config_timezone: Africa/Cairo
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
      - name: ✨ Generate Achievements
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/achievements.svg
          user: abdulrahman1s
          template: classic
          base: ""
          config_timezone: Africa/Cairo
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
      - name: 👀 Generate Recent articles
        uses: lowlighter/metrics@latest
        with:
          token: NOT_NEEDED
          user: abdulrahman1s
          filename: assets/articles.svg
          template: classic
          base: ""
          plugin_posts: yes
          plugin_posts_limit: 5
          plugin_posts_source: dev.to
          plugin_posts_user: abdulrahman1s
