name: Update Bio
on:
  schedule: [{ cron: "0 */3 * * *" }] # Runs every 3 hours
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    env: 
       QUOTES_URI: https://raw.githubusercontent.com/abdulrahman1s/abdulrahman1s/master/assets/prophet-muhammad-quotes.txt
       SIGNATURE: "- Prophet Muhammad (ﷺ)"
    steps: 
      - run: >
          curl
          --request PATCH
          --header "Authorization: Bearer ${{ secrets.GH_TOKEN }}"
          --data "{\"bio\": \"$(curl -sS $QUOTES_URI | shuf -n 1) $SIGNATURE\" }" 
          --silent
          --output /dev/null
          https://api.github.com/user
