name: Update Bio

on:
  schedule: [{cron: "0 */3 * * *"}]
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - run: curl -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" -d '{"bio": "$(shuf -n 1 ./assets/prophet-muhammad-quotes.txt)" }' https://api.github.com/user
    - run: echo "Done!"
